disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Portfolio"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Mati Jensen"
#   email = "youremail@example.com"
   image = "pfp.jpg"
#   imageQuality = 96
   headline = """
   Passionate Game Developer with an MsC in Game Design & Technology, BsC in Software.

   I have a strong foundation in software from university, and many game development projects including both collaborative and solo projects, in university and as personal projects,
   where i have learned the fundamentals of every side of game development, including helping release a small paid game on Itch.io.

   I specialize in graphics with a masters thesis is Screen-Space Global Illumination using Radiance Cascades. 
   Though I also have experience in other technical game development topics needed to ship a game from start to end, such as physics, tooling, dynamic audio and music, tech art, pathfinding, procedural generation, etc, from developing independent games and projects as a hobby and in university.   
   
   I hope to be able to contribute and help designers and artists create original projects requiring unique solutions, and to be able to contribute to the direction of the projects I am working on.
   
   """
   bio = "A little bit about you"
   links = [
     { email = "mailto:migogmati@gmail.com" },
#     { link = "https://link-to-some-website.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { bluesky = "https://bsky.app/profile/username" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
#     { github = "https://github.com/username" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
     { itch-io = "https://bitilope.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
     { linkedin = "https://linkedin.com/in/mati-jensen" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
   ]
